# Generated by Django 5.1.7 on 2025-03-13 23:08

from django.db import migrations

def populate_status(apps, schemaeditor):
    statuses = {
        "published":"A post that is visible to all on the site.",
        "draft":"A post that only the author can see and interact with.",
        "archived":"A post that is only visible to all logged users."
    }
    Status = apps.get_model("posts", "Status")
    for key, value in statuses.items():
        status_obj = Status(name=key, description=value)
        status_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_status)
    ]
